TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt

HEADERS += \
    src/array.h \
    src/constants.h \
    src/math.h \
    src/matrix.h \
    third_party/eigen/src/Cholesky/LDLT.h \
    third_party/eigen/src/Cholesky/LLT.h \
    third_party/eigen/src/Cholesky/LLT_LAPACKE.h \
    third_party/eigen/src/Core/arch/AltiVec/Complex.h \
    third_party/eigen/src/Core/arch/AltiVec/MathFunctions.h \
    third_party/eigen/src/Core/arch/AltiVec/PacketMath.h \
    third_party/eigen/src/Core/arch/AVX/Complex.h \
    third_party/eigen/src/Core/arch/AVX/MathFunctions.h \
    third_party/eigen/src/Core/arch/AVX/PacketMath.h \
    third_party/eigen/src/Core/arch/AVX/TypeCasting.h \
    third_party/eigen/src/Core/arch/AVX512/MathFunctions.h \
    third_party/eigen/src/Core/arch/AVX512/PacketMath.h \
    third_party/eigen/src/Core/arch/CUDA/Complex.h \
    third_party/eigen/src/Core/arch/CUDA/Half.h \
    third_party/eigen/src/Core/arch/CUDA/MathFunctions.h \
    third_party/eigen/src/Core/arch/CUDA/PacketMath.h \
    third_party/eigen/src/Core/arch/CUDA/PacketMathHalf.h \
    third_party/eigen/src/Core/arch/CUDA/TypeCasting.h \
    third_party/eigen/src/Core/arch/Default/Settings.h \
    third_party/eigen/src/Core/arch/NEON/Complex.h \
    third_party/eigen/src/Core/arch/NEON/MathFunctions.h \
    third_party/eigen/src/Core/arch/NEON/PacketMath.h \
    third_party/eigen/src/Core/arch/SSE/Complex.h \
    third_party/eigen/src/Core/arch/SSE/MathFunctions.h \
    third_party/eigen/src/Core/arch/SSE/PacketMath.h \
    third_party/eigen/src/Core/arch/SSE/TypeCasting.h \
    third_party/eigen/src/Core/arch/ZVector/Complex.h \
    third_party/eigen/src/Core/arch/ZVector/MathFunctions.h \
    third_party/eigen/src/Core/arch/ZVector/PacketMath.h \
    third_party/eigen/src/Core/functors/AssignmentFunctors.h \
    third_party/eigen/src/Core/functors/BinaryFunctors.h \
    third_party/eigen/src/Core/functors/NullaryFunctors.h \
    third_party/eigen/src/Core/functors/StlFunctors.h \
    third_party/eigen/src/Core/functors/TernaryFunctors.h \
    third_party/eigen/src/Core/functors/UnaryFunctors.h \
    third_party/eigen/src/Core/products/GeneralBlockPanelKernel.h \
    third_party/eigen/src/Core/products/GeneralMatrixMatrix.h \
    third_party/eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
    third_party/eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
    third_party/eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
    third_party/eigen/src/Core/products/GeneralMatrixVector.h \
    third_party/eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
    third_party/eigen/src/Core/products/Parallelizer.h \
    third_party/eigen/src/Core/products/SelfadjointMatrixMatrix.h \
    third_party/eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
    third_party/eigen/src/Core/products/SelfadjointMatrixVector.h \
    third_party/eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
    third_party/eigen/src/Core/products/SelfadjointProduct.h \
    third_party/eigen/src/Core/products/SelfadjointRank2Update.h \
    third_party/eigen/src/Core/products/TriangularMatrixMatrix.h \
    third_party/eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
    third_party/eigen/src/Core/products/TriangularMatrixVector.h \
    third_party/eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
    third_party/eigen/src/Core/products/TriangularSolverMatrix.h \
    third_party/eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
    third_party/eigen/src/Core/products/TriangularSolverVector.h \
    third_party/eigen/src/Core/util/BlasUtil.h \
    third_party/eigen/src/Core/util/Constants.h \
    third_party/eigen/src/Core/util/DisableStupidWarnings.h \
    third_party/eigen/src/Core/util/ForwardDeclarations.h \
    third_party/eigen/src/Core/util/Macros.h \
    third_party/eigen/src/Core/util/Memory.h \
    third_party/eigen/src/Core/util/Meta.h \
    third_party/eigen/src/Core/util/MKL_support.h \
    third_party/eigen/src/Core/util/NonMPL2.h \
    third_party/eigen/src/Core/util/ReenableStupidWarnings.h \
    third_party/eigen/src/Core/util/StaticAssert.h \
    third_party/eigen/src/Core/util/XprHelper.h \
    third_party/eigen/src/Core/Array.h \
    third_party/eigen/src/Core/ArrayBase.h \
    third_party/eigen/src/Core/ArrayWrapper.h \
    third_party/eigen/src/Core/Assign.h \
    third_party/eigen/src/Core/Assign_MKL.h \
    third_party/eigen/src/Core/AssignEvaluator.h \
    third_party/eigen/src/Core/BandMatrix.h \
    third_party/eigen/src/Core/Block.h \
    third_party/eigen/src/Core/BooleanRedux.h \
    third_party/eigen/src/Core/CommaInitializer.h \
    third_party/eigen/src/Core/ConditionEstimator.h \
    third_party/eigen/src/Core/CoreEvaluators.h \
    third_party/eigen/src/Core/CoreIterators.h \
    third_party/eigen/src/Core/CwiseBinaryOp.h \
    third_party/eigen/src/Core/CwiseNullaryOp.h \
    third_party/eigen/src/Core/CwiseTernaryOp.h \
    third_party/eigen/src/Core/CwiseUnaryOp.h \
    third_party/eigen/src/Core/CwiseUnaryView.h \
    third_party/eigen/src/Core/DenseBase.h \
    third_party/eigen/src/Core/DenseCoeffsBase.h \
    third_party/eigen/src/Core/DenseStorage.h \
    third_party/eigen/src/Core/Diagonal.h \
    third_party/eigen/src/Core/DiagonalMatrix.h \
    third_party/eigen/src/Core/DiagonalProduct.h \
    third_party/eigen/src/Core/Dot.h \
    third_party/eigen/src/Core/EigenBase.h \
    third_party/eigen/src/Core/ForceAlignedAccess.h \
    third_party/eigen/src/Core/Fuzzy.h \
    third_party/eigen/src/Core/GeneralProduct.h \
    third_party/eigen/src/Core/GenericPacketMath.h \
    third_party/eigen/src/Core/GlobalFunctions.h \
    third_party/eigen/src/Core/Inverse.h \
    third_party/eigen/src/Core/IO.h \
    third_party/eigen/src/Core/Map.h \
    third_party/eigen/src/Core/MapBase.h \
    third_party/eigen/src/Core/MathFunctions.h \
    third_party/eigen/src/Core/MathFunctionsImpl.h \
    third_party/eigen/src/Core/Matrix.h \
    third_party/eigen/src/Core/MatrixBase.h \
    third_party/eigen/src/Core/NestByValue.h \
    third_party/eigen/src/Core/NoAlias.h \
    third_party/eigen/src/Core/NumTraits.h \
    third_party/eigen/src/Core/PermutationMatrix.h \
    third_party/eigen/src/Core/PlainObjectBase.h \
    third_party/eigen/src/Core/Product.h \
    third_party/eigen/src/Core/ProductEvaluators.h \
    third_party/eigen/src/Core/Random.h \
    third_party/eigen/src/Core/Redux.h \
    third_party/eigen/src/Core/Ref.h \
    third_party/eigen/src/Core/Replicate.h \
    third_party/eigen/src/Core/ReturnByValue.h \
    third_party/eigen/src/Core/Reverse.h \
    third_party/eigen/src/Core/Select.h \
    third_party/eigen/src/Core/SelfAdjointView.h \
    third_party/eigen/src/Core/SelfCwiseBinaryOp.h \
    third_party/eigen/src/Core/Solve.h \
    third_party/eigen/src/Core/SolverBase.h \
    third_party/eigen/src/Core/SolveTriangular.h \
    third_party/eigen/src/Core/StableNorm.h \
    third_party/eigen/src/Core/Stride.h \
    third_party/eigen/src/Core/Swap.h \
    third_party/eigen/src/Core/Transpose.h \
    third_party/eigen/src/Core/Transpositions.h \
    third_party/eigen/src/Core/TriangularMatrix.h \
    third_party/eigen/src/Core/VectorBlock.h \
    third_party/eigen/src/Core/VectorwiseOp.h \
    third_party/eigen/src/Core/Visitor.h \
    third_party/eigen/src/Eigenvalues/ComplexEigenSolver.h \
    third_party/eigen/src/Eigenvalues/ComplexSchur.h \
    third_party/eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
    third_party/eigen/src/Eigenvalues/EigenSolver.h \
    third_party/eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
    third_party/eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
    third_party/eigen/src/Eigenvalues/HessenbergDecomposition.h \
    third_party/eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
    third_party/eigen/src/Eigenvalues/RealQZ.h \
    third_party/eigen/src/Eigenvalues/RealSchur.h \
    third_party/eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
    third_party/eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
    third_party/eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h \
    third_party/eigen/src/Eigenvalues/Tridiagonalization.h \
    third_party/eigen/src/Geometry/arch/Geometry_SSE.h \
    third_party/eigen/src/Geometry/AlignedBox.h \
    third_party/eigen/src/Geometry/AngleAxis.h \
    third_party/eigen/src/Geometry/EulerAngles.h \
    third_party/eigen/src/Geometry/Homogeneous.h \
    third_party/eigen/src/Geometry/Hyperplane.h \
    third_party/eigen/src/Geometry/OrthoMethods.h \
    third_party/eigen/src/Geometry/ParametrizedLine.h \
    third_party/eigen/src/Geometry/Quaternion.h \
    third_party/eigen/src/Geometry/Rotation2D.h \
    third_party/eigen/src/Geometry/RotationBase.h \
    third_party/eigen/src/Geometry/Scaling.h \
    third_party/eigen/src/Geometry/Transform.h \
    third_party/eigen/src/Geometry/Translation.h \
    third_party/eigen/src/Geometry/Umeyama.h \
    third_party/eigen/src/Householder/BlockHouseholder.h \
    third_party/eigen/src/Householder/Householder.h \
    third_party/eigen/src/Householder/HouseholderSequence.h \
    third_party/eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
    third_party/eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
    third_party/eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
    third_party/eigen/src/IterativeLinearSolvers/IncompleteCholesky.h \
    third_party/eigen/src/IterativeLinearSolvers/IncompleteLUT.h \
    third_party/eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
    third_party/eigen/src/IterativeLinearSolvers/LeastSquareConjugateGradient.h \
    third_party/eigen/src/IterativeLinearSolvers/SolveWithGuess.h \
    third_party/eigen/src/Jacobi/Jacobi.h \
    third_party/eigen/src/LU/arch/Inverse_SSE.h \
    third_party/eigen/src/LU/Determinant.h \
    third_party/eigen/src/LU/FullPivLU.h \
    third_party/eigen/src/LU/InverseImpl.h \
    third_party/eigen/src/LU/PartialPivLU.h \
    third_party/eigen/src/LU/PartialPivLU_LAPACKE.h \
    third_party/eigen/src/misc/blas.h \
    third_party/eigen/src/misc/Image.h \
    third_party/eigen/src/misc/Kernel.h \
    third_party/eigen/src/misc/lapack.h \
    third_party/eigen/src/misc/lapacke.h \
    third_party/eigen/src/misc/lapacke_mangling.h \
    third_party/eigen/src/misc/RealSvd2x2.h \
    third_party/eigen/src/OrderingMethods/Amd.h \
    third_party/eigen/src/OrderingMethods/Eigen_Colamd.h \
    third_party/eigen/src/OrderingMethods/Ordering.h \
    third_party/eigen/src/plugins/ArrayCwiseBinaryOps.h \
    third_party/eigen/src/plugins/ArrayCwiseUnaryOps.h \
    third_party/eigen/src/plugins/BlockMethods.h \
    third_party/eigen/src/plugins/CommonCwiseBinaryOps.h \
    third_party/eigen/src/plugins/CommonCwiseUnaryOps.h \
    third_party/eigen/src/plugins/MatrixCwiseBinaryOps.h \
    third_party/eigen/src/plugins/MatrixCwiseUnaryOps.h \
    third_party/eigen/src/QR/ColPivHouseholderQR.h \
    third_party/eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
    third_party/eigen/src/QR/CompleteOrthogonalDecomposition.h \
    third_party/eigen/src/QR/FullPivHouseholderQR.h \
    third_party/eigen/src/QR/HouseholderQR.h \
    third_party/eigen/src/QR/HouseholderQR_LAPACKE.h \
    third_party/eigen/src/StlSupport/details.h \
    third_party/eigen/src/StlSupport/StdDeque.h \
    third_party/eigen/src/StlSupport/StdList.h \
    third_party/eigen/src/StlSupport/StdVector.h \
    third_party/eigen/src/SVD/BDCSVD.h \
    third_party/eigen/src/SVD/JacobiSVD.h \
    third_party/eigen/src/SVD/JacobiSVD_LAPACKE.h \
    third_party/eigen/src/SVD/SVDBase.h \
    third_party/eigen/src/SVD/UpperBidiagonalization.h \
    third_party/eigen/Cholesky \
    third_party/eigen/Core \
    third_party/eigen/Dense \
    third_party/eigen/Eigen \
    third_party/eigen/Eigenvalues \
    third_party/eigen/Geometry \
    third_party/eigen/Householder \
    third_party/eigen/IterativeLinearSolvers \
    third_party/eigen/Jacobi \
    third_party/eigen/LU \
    third_party/eigen/OrderingMethods \
    third_party/eigen/QR \
    third_party/eigen/QtAlignedMalloc \
    third_party/eigen/StdDeque \
    third_party/eigen/StdList \
    third_party/eigen/StdVector \
    third_party/eigen/SVD \
    src/linear_algebra/gauss_solver.h \
    src/linear_algebra/tridiagonal_matrix_solver.h \
    src/linear_algebra/jacobi_solver.h \
    src/linear_algebra/gauss_seidel_solver.h \
    tests/linear_algebra_test.h \
    src/linear_algebra/jacobi_eigenvalues.h \
    src/linear_algebra/lu_decomposition.h \
    src/linear_algebra/qr_eigenvalues.h \
    src/nonlinear_equations/bisection_method.h \
    src/nonlinear_equations/function.h \
    src/nonlinear_equations/newtons_method.h \
    tests/nonlinear_equations_test.h

SOURCES += \
    src/main.cc \
    src/matrix.cc \
    src/linear_algebra/gauss_solver.cc \
    src/linear_algebra/tridiagonal_matrix_solver.cc \
    src/linear_algebra/jacobi_solver.cc \
    src/linear_algebra/gauss_seidel_solver.cc \
    tests/linear_algebra_test.cc \
    src/linear_algebra/jacobi_eigenvalues.cc \
    src/linear_algebra/lu_decomposition.cc \
    src/linear_algebra/qr_eigenvalues.cc \
    src/nonlinear_equations/bisection_method.cc \
    src/nonlinear_equations/newtons_method.cc \
    tests/nonlinear_equations_test.cc

DISTFILES +=
